[2023-04-12T09:23:14.921+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_extraction_dag.upload_positions_to_gcs manual__2023-04-12T09:16:47.753380+00:00 [queued]>
[2023-04-12T09:23:14.934+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_extraction_dag.upload_positions_to_gcs manual__2023-04-12T09:16:47.753380+00:00 [queued]>
[2023-04-12T09:23:14.935+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T09:23:14.936+0000] {taskinstance.py:1289} INFO - Starting attempt 3 of 4
[2023-04-12T09:23:14.937+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T09:23:14.956+0000] {taskinstance.py:1309} INFO - Executing <Task(_PythonDecoratedOperator): upload_positions_to_gcs> on 2023-04-12 09:16:47.753380+00:00
[2023-04-12T09:23:14.963+0000] {standard_task_runner.py:55} INFO - Started process 5243 to run task
[2023-04-12T09:23:14.965+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_extraction_dag', 'upload_positions_to_gcs', 'manual__2023-04-12T09:16:47.753380+00:00', '--job-id', '700', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpmv371dz9']
[2023-04-12T09:23:14.969+0000] {standard_task_runner.py:83} INFO - Job 700: Subtask upload_positions_to_gcs
[2023-04-12T09:23:15.049+0000] {task_command.py:389} INFO - Running <TaskInstance: data_extraction_dag.upload_positions_to_gcs manual__2023-04-12T09:16:47.753380+00:00 [running]> on host a2e619923d04
[2023-04-12T09:23:15.126+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_extraction_dag
AIRFLOW_CTX_TASK_ID=upload_positions_to_gcs
AIRFLOW_CTX_EXECUTION_DATE=2023-04-12T09:16:47.753380+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-12T09:16:47.753380+00:00
[2023-04-12T09:23:15.129+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-12T09:23:15.132+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'gsutil cp -r /opt/***/csv gs://nfl-data-lake_nfl-de-project/nfl_csv/']
[2023-04-12T09:23:15.151+0000] {subprocess.py:86} INFO - Output:
[2023-04-12T09:23:15.417+0000] {taskinstance.py:1080} INFO - Dependencies not met for <TaskInstance: data_extraction_dag.upload_positions_to_gcs manual__2023-04-12T09:16:47.753380+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2023-04-12T09:23:15.427+0000] {taskinstance.py:1080} INFO - Dependencies not met for <TaskInstance: data_extraction_dag.upload_positions_to_gcs manual__2023-04-12T09:16:47.753380+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2023-04-12T09:23:15.432+0000] {local_task_job.py:151} INFO - Task is not able to be run
[2023-04-12T09:23:19.891+0000] {subprocess.py:93} INFO - Copying file:///opt/***/csv/positions_csv.csv [Content-Type=text/csv]...
[2023-04-12T09:23:21.804+0000] {subprocess.py:93} INFO - / [0 files][    0.0 B/  476.0 B]                                                -ServiceException: 401 Anonymous caller does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist).
[2023-04-12T09:23:22.473+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-12T09:23:22.504+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion.py", line 157, in upload_positions_to_gcs
    operator.execute(context={})
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-12T09:23:22.521+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=data_extraction_dag, task_id=upload_positions_to_gcs, execution_date=20230412T091647, start_date=20230412T092314, end_date=20230412T092322
[2023-04-12T09:23:22.553+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 700 for task upload_positions_to_gcs (Bash command failed. The command returned a non-zero exit code 1.; 5243)
[2023-04-12T09:23:22.585+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-12T09:23:22.610+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
