[2023-04-23T08:35:05.830+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_extraction_dag.task_athletes manual__2023-04-23T08:23:43.182997+00:00 [queued]>
[2023-04-23T08:35:05.848+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_extraction_dag.task_athletes manual__2023-04-23T08:23:43.182997+00:00 [queued]>
[2023-04-23T08:35:05.849+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T08:35:05.850+0000] {taskinstance.py:1289} INFO - Starting attempt 2 of 3
[2023-04-23T08:35:05.851+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T08:35:05.873+0000] {taskinstance.py:1309} INFO - Executing <Task(_PythonDecoratedOperator): task_athletes> on 2023-04-23 08:23:43.182997+00:00
[2023-04-23T08:35:05.891+0000] {standard_task_runner.py:55} INFO - Started process 5168 to run task
[2023-04-23T08:35:05.927+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_extraction_dag', 'task_athletes', 'manual__2023-04-23T08:23:43.182997+00:00', '--job-id', '1022', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpcaieb2xu']
[2023-04-23T08:35:05.956+0000] {standard_task_runner.py:83} INFO - Job 1022: Subtask task_athletes
[2023-04-23T08:35:06.252+0000] {task_command.py:389} INFO - Running <TaskInstance: data_extraction_dag.task_athletes manual__2023-04-23T08:23:43.182997+00:00 [running]> on host 235fa867d994
[2023-04-23T08:35:06.511+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_extraction_dag
AIRFLOW_CTX_TASK_ID=task_athletes
AIRFLOW_CTX_EXECUTION_DATE=2023-04-23T08:23:43.182997+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-23T08:23:43.182997+00:00
[2023-04-23T08:35:06.514+0000] {logging_mixin.py:137} INFO - Fetching for athlete details started
[2023-04-23T08:41:17.787+0000] {timeout.py:68} ERROR - Process timed out, PID: 5168
[2023-04-23T08:41:17.865+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion.py", line 115, in task_athletes
    athletes=get_athletes(athlete_ids, year).to_json()
  File "/opt/airflow/code/extraction_nfl.py", line 370, in get_athletes
    athletes_df=pd.concat(athletes_df_list, ignore_index=True)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 381, in concat
    return op.get_result()
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 616, in get_result
    new_data = concatenate_managers(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/internals/concat.py", line 205, in concatenate_managers
    for placement, join_units in concat_plan:
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/internals/concat.py", line 760, in _combine_concat_plans
    next_items[i] = (plc[min_len:], _trim_join_unit(unit, min_len))
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: Timeout, PID: 5168
[2023-04-23T08:41:17.905+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=data_extraction_dag, task_id=task_athletes, execution_date=20230423T082343, start_date=20230423T083505, end_date=20230423T084117
[2023-04-23T08:41:17.952+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 1022 for task task_athletes (Timeout, PID: 5168; 5168)
[2023-04-23T08:41:18.192+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-23T08:41:18.589+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
