[2023-04-23T10:10:13.350+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_extraction_dag.task_teams manual__2023-04-23T09:57:33+00:00 [queued]>
[2023-04-23T10:10:13.364+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_extraction_dag.task_teams manual__2023-04-23T09:57:33+00:00 [queued]>
[2023-04-23T10:10:13.365+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T10:10:13.366+0000] {taskinstance.py:1289} INFO - Starting attempt 4 of 5
[2023-04-23T10:10:13.367+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T10:10:13.385+0000] {taskinstance.py:1309} INFO - Executing <Task(_PythonDecoratedOperator): task_teams> on 2023-04-23 09:57:33+00:00
[2023-04-23T10:10:13.395+0000] {standard_task_runner.py:55} INFO - Started process 4145 to run task
[2023-04-23T10:10:13.400+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_extraction_dag', 'task_teams', 'manual__2023-04-23T09:57:33+00:00', '--job-id', '1159', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmp06ypcbqf']
[2023-04-23T10:10:13.404+0000] {standard_task_runner.py:83} INFO - Job 1159: Subtask task_teams
[2023-04-23T10:10:13.524+0000] {task_command.py:389} INFO - Running <TaskInstance: data_extraction_dag.task_teams manual__2023-04-23T09:57:33+00:00 [running]> on host 235fa867d994
[2023-04-23T10:10:13.596+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_extraction_dag
AIRFLOW_CTX_TASK_ID=task_teams
AIRFLOW_CTX_EXECUTION_DATE=2023-04-23T09:57:33+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-23T09:57:33+00:00
[2023-04-23T10:10:13.598+0000] {logging_mixin.py:137} INFO - Fetching for teams started
[2023-04-23T10:10:14.363+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion.py", line 105, in task_teams
    teams=get_teams(teamIds, year).to_json()
  File "/opt/airflow/code/extraction_nfl.py", line 93, in get_teams
    teams_df=pd.concat(teams_df_list, ignore_index=True)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 368, in concat
    op = _Concatenator(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 425, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
[2023-04-23T10:10:14.387+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=data_extraction_dag, task_id=task_teams, execution_date=20230423T095733, start_date=20230423T101013, end_date=20230423T101014
[2023-04-23T10:10:14.407+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 1159 for task task_teams (No objects to concatenate; 4145)
[2023-04-23T10:10:14.457+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-23T10:10:14.490+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
