[2023-04-23T10:10:10.674+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_extraction_dag.task_teams_stats manual__2023-04-23T09:57:33+00:00 [queued]>
[2023-04-23T10:10:10.696+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_extraction_dag.task_teams_stats manual__2023-04-23T09:57:33+00:00 [queued]>
[2023-04-23T10:10:10.697+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T10:10:10.698+0000] {taskinstance.py:1289} INFO - Starting attempt 4 of 5
[2023-04-23T10:10:10.699+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T10:10:10.723+0000] {taskinstance.py:1309} INFO - Executing <Task(_PythonDecoratedOperator): task_teams_stats> on 2023-04-23 09:57:33+00:00
[2023-04-23T10:10:10.750+0000] {standard_task_runner.py:55} INFO - Started process 4112 to run task
[2023-04-23T10:10:10.768+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_extraction_dag', 'task_teams_stats', 'manual__2023-04-23T09:57:33+00:00', '--job-id', '1157', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmp71hx2k3l']
[2023-04-23T10:10:10.794+0000] {standard_task_runner.py:83} INFO - Job 1157: Subtask task_teams_stats
[2023-04-23T10:10:11.252+0000] {task_command.py:389} INFO - Running <TaskInstance: data_extraction_dag.task_teams_stats manual__2023-04-23T09:57:33+00:00 [running]> on host 235fa867d994
[2023-04-23T10:10:11.394+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_extraction_dag
AIRFLOW_CTX_TASK_ID=task_teams_stats
AIRFLOW_CTX_EXECUTION_DATE=2023-04-23T09:57:33+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-23T09:57:33+00:00
[2023-04-23T10:10:11.396+0000] {logging_mixin.py:137} INFO - Fetching for teams_stats started
[2023-04-23T10:10:12.189+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion.py", line 110, in task_teams_stats
    teams_stats=get_teams_stats(teamIds, year, season_type).to_json()
  File "/opt/airflow/code/extraction_nfl.py", line 153, in get_teams_stats
    stats_dfs=pd.concat(teams_stats_list, ignore_index=True).fillna(0)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 368, in concat
    op = _Concatenator(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 425, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
[2023-04-23T10:10:12.208+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=data_extraction_dag, task_id=task_teams_stats, execution_date=20230423T095733, start_date=20230423T101010, end_date=20230423T101012
[2023-04-23T10:10:12.226+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 1157 for task task_teams_stats (No objects to concatenate; 4112)
[2023-04-23T10:10:12.276+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-23T10:10:12.312+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
