[2023-04-23T10:05:12.172+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_extraction_dag.task_athlete_stats manual__2023-04-23T09:57:33+00:00 [queued]>
[2023-04-23T10:05:12.186+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_extraction_dag.task_athlete_stats manual__2023-04-23T09:57:33+00:00 [queued]>
[2023-04-23T10:05:12.187+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T10:05:12.188+0000] {taskinstance.py:1289} INFO - Starting attempt 2 of 4
[2023-04-23T10:05:12.189+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T10:05:12.206+0000] {taskinstance.py:1309} INFO - Executing <Task(_PythonDecoratedOperator): task_athlete_stats> on 2023-04-23 09:57:33+00:00
[2023-04-23T10:05:12.217+0000] {standard_task_runner.py:55} INFO - Started process 3765 to run task
[2023-04-23T10:05:12.222+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_extraction_dag', 'task_athlete_stats', 'manual__2023-04-23T09:57:33+00:00', '--job-id', '1154', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpu0x96kuy']
[2023-04-23T10:05:12.225+0000] {standard_task_runner.py:83} INFO - Job 1154: Subtask task_athlete_stats
[2023-04-23T10:05:12.331+0000] {task_command.py:389} INFO - Running <TaskInstance: data_extraction_dag.task_athlete_stats manual__2023-04-23T09:57:33+00:00 [running]> on host 235fa867d994
[2023-04-23T10:05:12.480+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_extraction_dag
AIRFLOW_CTX_TASK_ID=task_athlete_stats
AIRFLOW_CTX_EXECUTION_DATE=2023-04-23T09:57:33+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-23T09:57:33+00:00
[2023-04-23T10:05:12.508+0000] {logging_mixin.py:137} INFO - Fetching for athlete stats started
[2023-04-23T10:07:18.156+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion.py", line 120, in task_athlete_stats
    athletes_stats=get_athletes_stats(athlete_ids, year, season_type).to_json()
  File "/opt/airflow/code/extraction_nfl.py", line 302, in get_athletes_stats
    athletes_stats=pd.concat(athletes_df_list, ignore_index=True)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 368, in concat
    op = _Concatenator(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 425, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
[2023-04-23T10:07:18.224+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=data_extraction_dag, task_id=task_athlete_stats, execution_date=20230423T095733, start_date=20230423T100512, end_date=20230423T100718
[2023-04-23T10:07:18.280+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 1154 for task task_athlete_stats (No objects to concatenate; 3765)
[2023-04-23T10:07:18.351+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-23T10:07:18.405+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
