[2023-04-12T11:47:54.496+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [queued]>
[2023-04-12T11:47:54.508+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [queued]>
[2023-04-12T11:47:54.509+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T11:47:54.510+0000] {taskinstance.py:1289} INFO - Starting attempt 7 of 8
[2023-04-12T11:47:54.511+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T11:47:54.529+0000] {taskinstance.py:1309} INFO - Executing <Task(_PythonDecoratedOperator): task_pyspark> on 2023-04-11 00:00:00+00:00
[2023-04-12T11:47:54.530+0000] {taskinstance.py:1080} INFO - Dependencies not met for <TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2023-04-12T11:47:54.531+0000] {taskinstance.py:1080} INFO - Dependencies not met for <TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2023-04-12T11:47:54.543+0000] {local_task_job.py:151} INFO - Task is not able to be run
[2023-04-12T11:47:54.546+0000] {standard_task_runner.py:55} INFO - Started process 6944 to run task
[2023-04-12T11:47:54.550+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'nfl_transformation_dag', 'task_pyspark', 'scheduled__2023-04-11T00:00:00+00:00', '--job-id', '929', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpmpkgj2m5']
[2023-04-12T11:47:54.552+0000] {standard_task_runner.py:83} INFO - Job 929: Subtask task_pyspark
[2023-04-12T11:47:54.636+0000] {task_command.py:389} INFO - Running <TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [running]> on host a2e619923d04
[2023-04-12T11:47:54.723+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nfl_transformation_dag
AIRFLOW_CTX_TASK_ID=task_pyspark
AIRFLOW_CTX_EXECUTION_DATE=2023-04-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=7
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-11T00:00:00+00:00
[2023-04-12T11:47:54.745+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-12T11:47:54.755+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'gcloud dataproc jobs submit pyspark                 --cluster=nfl-spark-cluster                 --region=europe-west6                 gs://nfl-data-lake_nfl-de-project/code/transform_pyspark.py                 --                     --year=2020                     --season_type=2 ']
[2023-04-12T11:47:54.777+0000] {subprocess.py:86} INFO - Output:
[2023-04-12T11:48:00.899+0000] {subprocess.py:93} INFO - Job [67857a6d4600410e89ce4f133b731f79] submitted.
[2023-04-12T11:48:00.901+0000] {subprocess.py:93} INFO - Waiting for job output...
[2023-04-12T11:48:10.717+0000] {subprocess.py:93} INFO - 23/04/12 11:48:02 INFO org.apache.spark.SparkEnv: Registering MapOutputTracker
[2023-04-12T11:48:10.718+0000] {subprocess.py:93} INFO - 23/04/12 11:48:02 INFO org.apache.spark.SparkEnv: Registering BlockManagerMaster
[2023-04-12T11:48:10.719+0000] {subprocess.py:93} INFO - 23/04/12 11:48:02 INFO org.apache.spark.SparkEnv: Registering BlockManagerMasterHeartbeat
[2023-04-12T11:48:10.720+0000] {subprocess.py:93} INFO - 23/04/12 11:48:02 INFO org.apache.spark.SparkEnv: Registering OutputCommitCoordinator
[2023-04-12T11:48:10.721+0000] {subprocess.py:93} INFO - 23/04/12 11:48:02 INFO org.sparkproject.jetty.util.log: Logging initialized @3961ms to org.sparkproject.jetty.util.log.Slf4jLog
[2023-04-12T11:48:10.722+0000] {subprocess.py:93} INFO - 23/04/12 11:48:02 INFO org.sparkproject.jetty.server.Server: jetty-9.4.40.v20210413; built: 2021-04-13T20:42:42.668Z; git: b881a572662e1943a14ae12e7e1207989f218b74; jvm 1.8.0_322-b06
[2023-04-12T11:48:10.722+0000] {subprocess.py:93} INFO - 23/04/12 11:48:02 INFO org.sparkproject.jetty.server.Server: Started @4088ms
[2023-04-12T11:48:10.723+0000] {subprocess.py:93} INFO - 23/04/12 11:48:02 INFO org.sparkproject.jetty.server.AbstractConnector: Started ServerConnector@6c8efa96{HTTP/1.1, (http/1.1)}{0.0.0.0:35935}
[2023-04-12T11:48:14.775+0000] {subprocess.py:93} INFO - 23/04/12 11:48:05 INFO com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl: Ignoring exception of type GoogleJsonResponseException; verified object already exists with desired state.
[2023-04-12T11:48:20.368+0000] {subprocess.py:93} INFO - 23/04/12 11:48:12 WARN org.apache.spark.sql.catalyst.util.package: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.
[2023-04-12T11:48:20.369+0000] {subprocess.py:93} INFO - Cleaning the data for the teams_df started
[2023-04-12T11:48:20.370+0000] {subprocess.py:93} INFO - Cleaning the data for the teams_df is successful!
[2023-04-12T11:48:23.467+0000] {subprocess.py:93} INFO - Loading for nfl data to parquet started
[2023-04-12T11:48:23.468+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-04-12T11:48:23.468+0000] {subprocess.py:93} INFO -   File "/tmp/67857a6d4600410e89ce4f133b731f79/transform_pyspark.py", line 231, in <module>
[2023-04-12T11:48:23.469+0000] {subprocess.py:93} INFO -     for df, filename in zip(df_list, filenames):
[2023-04-12T11:48:23.469+0000] {subprocess.py:93} INFO - NameError: name 'filenames' is not defined
[2023-04-12T11:48:23.470+0000] {subprocess.py:93} INFO - 23/04/12 11:48:18 INFO org.sparkproject.jetty.server.AbstractConnector: Stopped Spark@6c8efa96{HTTP/1.1, (http/1.1)}{0.0.0.0:0}
[2023-04-12T11:48:32.533+0000] {subprocess.py:93} INFO - ERROR: (gcloud.dataproc.jobs.submit.pyspark) Job [67857a6d4600410e89ce4f133b731f79] failed with error:
[2023-04-12T11:48:32.534+0000] {subprocess.py:93} INFO - Google Cloud Dataproc Agent reports job failure. If logs are available, they can be found at:
[2023-04-12T11:48:32.535+0000] {subprocess.py:93} INFO - https://console.cloud.google.com/dataproc/jobs/67857a6d4600410e89ce4f133b731f79?project=nfl-de-project&region=europe-west6
[2023-04-12T11:48:32.536+0000] {subprocess.py:93} INFO - gcloud dataproc jobs wait '67857a6d4600410e89ce4f133b731f79' --region 'europe-west6' --project 'nfl-de-project'
[2023-04-12T11:48:32.537+0000] {subprocess.py:93} INFO - https://console.cloud.google.com/storage/browser/nfl-spark-staging_nfl-de-project/google-cloud-dataproc-metainfo/cf386a87-5cdc-4f46-9dda-06a203a6bb84/jobs/67857a6d4600410e89ce4f133b731f79/
[2023-04-12T11:48:32.538+0000] {subprocess.py:93} INFO - gs://nfl-spark-staging_nfl-de-project/google-cloud-dataproc-metainfo/cf386a87-5cdc-4f46-9dda-06a203a6bb84/jobs/67857a6d4600410e89ce4f133b731f79/driveroutput
[2023-04-12T11:48:32.791+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-12T11:48:32.805+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion.py", line 223, in task_pyspark
    operator.execute(context={})
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-12T11:48:32.820+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=nfl_transformation_dag, task_id=task_pyspark, execution_date=20230411T000000, start_date=20230412T114754, end_date=20230412T114832
[2023-04-12T11:48:32.847+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 929 for task task_pyspark (Bash command failed. The command returned a non-zero exit code 1.; 6944)
[2023-04-12T11:48:32.865+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-12T11:48:32.882+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
