[2023-04-12T11:50:32.278+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [queued]>
[2023-04-12T11:50:32.298+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [queued]>
[2023-04-12T11:50:32.299+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T11:50:32.300+0000] {taskinstance.py:1289} INFO - Starting attempt 8 of 9
[2023-04-12T11:50:32.301+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T11:50:32.332+0000] {taskinstance.py:1309} INFO - Executing <Task(_PythonDecoratedOperator): task_pyspark> on 2023-04-11 00:00:00+00:00
[2023-04-12T11:50:32.336+0000] {taskinstance.py:1080} INFO - Dependencies not met for <TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2023-04-12T11:50:32.343+0000] {taskinstance.py:1080} INFO - Dependencies not met for <TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2023-04-12T11:50:32.363+0000] {local_task_job.py:151} INFO - Task is not able to be run
[2023-04-12T11:50:32.369+0000] {standard_task_runner.py:55} INFO - Started process 7046 to run task
[2023-04-12T11:50:32.402+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'nfl_transformation_dag', 'task_pyspark', 'scheduled__2023-04-11T00:00:00+00:00', '--job-id', '932', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpop0g037v']
[2023-04-12T11:50:32.405+0000] {standard_task_runner.py:83} INFO - Job 932: Subtask task_pyspark
[2023-04-12T11:50:32.523+0000] {task_command.py:389} INFO - Running <TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [running]> on host a2e619923d04
[2023-04-12T11:50:32.619+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nfl_transformation_dag
AIRFLOW_CTX_TASK_ID=task_pyspark
AIRFLOW_CTX_EXECUTION_DATE=2023-04-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=8
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-11T00:00:00+00:00
[2023-04-12T11:50:32.625+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-12T11:50:32.640+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'gcloud dataproc jobs submit pyspark                 --cluster=nfl-spark-cluster                 --region=europe-west6                 gs://nfl-data-lake_nfl-de-project/code/transform_pyspark.py                 --                     --year=2020                     --season_type=2 ']
[2023-04-12T11:50:32.674+0000] {subprocess.py:86} INFO - Output:
[2023-04-12T11:50:39.904+0000] {subprocess.py:93} INFO - Job [5f301b71494c4145b076d670b7e12c24] submitted.
[2023-04-12T11:50:39.905+0000] {subprocess.py:93} INFO - Waiting for job output...
[2023-04-12T11:50:51.064+0000] {subprocess.py:93} INFO - 23/04/12 11:50:44 INFO org.apache.spark.SparkEnv: Registering MapOutputTracker
[2023-04-12T11:50:51.064+0000] {subprocess.py:93} INFO - 23/04/12 11:50:44 INFO org.apache.spark.SparkEnv: Registering BlockManagerMaster
[2023-04-12T11:50:51.065+0000] {subprocess.py:93} INFO - 23/04/12 11:50:44 INFO org.apache.spark.SparkEnv: Registering BlockManagerMasterHeartbeat
[2023-04-12T11:50:51.065+0000] {subprocess.py:93} INFO - 23/04/12 11:50:44 INFO org.apache.spark.SparkEnv: Registering OutputCommitCoordinator
[2023-04-12T11:50:51.066+0000] {subprocess.py:93} INFO - 23/04/12 11:50:44 INFO org.sparkproject.jetty.util.log: Logging initialized @4172ms to org.sparkproject.jetty.util.log.Slf4jLog
[2023-04-12T11:50:51.066+0000] {subprocess.py:93} INFO - 23/04/12 11:50:44 INFO org.sparkproject.jetty.server.Server: jetty-9.4.40.v20210413; built: 2021-04-13T20:42:42.668Z; git: b881a572662e1943a14ae12e7e1207989f218b74; jvm 1.8.0_322-b06
[2023-04-12T11:50:51.067+0000] {subprocess.py:93} INFO - 23/04/12 11:50:44 INFO org.sparkproject.jetty.server.Server: Started @4314ms
[2023-04-12T11:50:51.068+0000] {subprocess.py:93} INFO - 23/04/12 11:50:44 INFO org.sparkproject.jetty.server.AbstractConnector: Started ServerConnector@5d0d99b2{HTTP/1.1, (http/1.1)}{0.0.0.0:46817}
[2023-04-12T11:50:51.069+0000] {subprocess.py:93} INFO - 23/04/12 11:50:47 INFO com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl: Ignoring exception of type GoogleJsonResponseException; verified object already exists with desired state.
[2023-04-12T11:51:01.483+0000] {subprocess.py:93} INFO - 23/04/12 11:50:54 WARN org.apache.spark.sql.catalyst.util.package: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.
[2023-04-12T11:51:01.484+0000] {subprocess.py:93} INFO - Cleaning the data for the teams_df started
[2023-04-12T11:51:01.485+0000] {subprocess.py:93} INFO - Cleaning the data for the teams_df is successful!
[2023-04-12T11:51:05.967+0000] {subprocess.py:93} INFO - Loading for nfl data to parquet started
[2023-04-12T11:51:05.967+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-04-12T11:51:05.969+0000] {subprocess.py:93} INFO -   File "/tmp/5f301b71494c4145b076d670b7e12c24/transform_pyspark.py", line 242, in <module>
[2023-04-12T11:51:05.970+0000] {subprocess.py:93} INFO -     df.write.format('bigquery') \
[2023-04-12T11:51:05.971+0000] {subprocess.py:93} INFO -   File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 1107, in save
[2023-04-12T11:51:05.972+0000] {subprocess.py:93} INFO -   File "/usr/lib/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1304, in __call__
[2023-04-12T11:51:05.973+0000] {subprocess.py:93} INFO -   File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 111, in deco
[2023-04-12T11:51:05.974+0000] {subprocess.py:93} INFO -   File "/usr/lib/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py", line 326, in get_return_value
[2023-04-12T11:51:05.976+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o274.save.
[2023-04-12T11:51:05.978+0000] {subprocess.py:93} INFO - : java.lang.ClassNotFoundException: Failed to find data source: bigquery. Please find packages at http://spark.apache.org/third-party-projects.html
[2023-04-12T11:51:05.979+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:692)
[2023-04-12T11:51:05.981+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSourceV2(DataSource.scala:746)
[2023-04-12T11:51:05.982+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.lookupV2Provider(DataFrameWriter.scala:993)
[2023-04-12T11:51:05.984+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:311)
[2023-04-12T11:51:05.985+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:301)
[2023-04-12T11:51:05.986+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-04-12T11:51:05.989+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-04-12T11:51:05.990+0000] {subprocess.py:93} INFO - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-04-12T11:51:05.992+0000] {subprocess.py:93} INFO - 	at java.lang.reflect.Method.invoke(Method.java:498)
[2023-04-12T11:51:05.994+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2023-04-12T11:51:05.995+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2023-04-12T11:51:05.996+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2023-04-12T11:51:05.997+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2023-04-12T11:51:05.999+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2023-04-12T11:51:06.000+0000] {subprocess.py:93} INFO - 	at py4j.GatewayConnection.run(GatewayConnection.java:238)
[2023-04-12T11:51:06.001+0000] {subprocess.py:93} INFO - 	at java.lang.Thread.run(Thread.java:750)
[2023-04-12T11:51:06.002+0000] {subprocess.py:93} INFO - Caused by: java.lang.ClassNotFoundException: bigquery.DefaultSource
[2023-04-12T11:51:06.003+0000] {subprocess.py:93} INFO - 	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
[2023-04-12T11:51:06.004+0000] {subprocess.py:93} INFO - 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[2023-04-12T11:51:06.005+0000] {subprocess.py:93} INFO - 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[2023-04-12T11:51:06.006+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$lookupDataSource$5(DataSource.scala:666)
[2023-04-12T11:51:06.007+0000] {subprocess.py:93} INFO - 	at scala.util.Try$.apply(Try.scala:213)
[2023-04-12T11:51:06.008+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$lookupDataSource$4(DataSource.scala:666)
[2023-04-12T11:51:06.009+0000] {subprocess.py:93} INFO - 	at scala.util.Failure.orElse(Try.scala:224)
[2023-04-12T11:51:06.010+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:666)
[2023-04-12T11:51:06.012+0000] {subprocess.py:93} INFO - 	... 15 more
[2023-04-12T11:51:06.012+0000] {subprocess.py:93} INFO - 
[2023-04-12T11:51:06.014+0000] {subprocess.py:93} INFO - 23/04/12 11:50:59 INFO org.sparkproject.jetty.server.AbstractConnector: Stopped Spark@5d0d99b2{HTTP/1.1, (http/1.1)}{0.0.0.0:0}
[2023-04-12T11:51:15.853+0000] {subprocess.py:93} INFO - ERROR: (gcloud.dataproc.jobs.submit.pyspark) Job [5f301b71494c4145b076d670b7e12c24] failed with error:
[2023-04-12T11:51:15.854+0000] {subprocess.py:93} INFO - Google Cloud Dataproc Agent reports job failure. If logs are available, they can be found at:
[2023-04-12T11:51:15.855+0000] {subprocess.py:93} INFO - https://console.cloud.google.com/dataproc/jobs/5f301b71494c4145b076d670b7e12c24?project=nfl-de-project&region=europe-west6
[2023-04-12T11:51:15.856+0000] {subprocess.py:93} INFO - gcloud dataproc jobs wait '5f301b71494c4145b076d670b7e12c24' --region 'europe-west6' --project 'nfl-de-project'
[2023-04-12T11:51:15.857+0000] {subprocess.py:93} INFO - https://console.cloud.google.com/storage/browser/nfl-spark-staging_nfl-de-project/google-cloud-dataproc-metainfo/cf386a87-5cdc-4f46-9dda-06a203a6bb84/jobs/5f301b71494c4145b076d670b7e12c24/
[2023-04-12T11:51:15.858+0000] {subprocess.py:93} INFO - gs://nfl-spark-staging_nfl-de-project/google-cloud-dataproc-metainfo/cf386a87-5cdc-4f46-9dda-06a203a6bb84/jobs/5f301b71494c4145b076d670b7e12c24/driveroutput
[2023-04-12T11:51:16.066+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-12T11:51:16.080+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion.py", line 223, in task_pyspark
    operator.execute(context={})
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-12T11:51:16.094+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=nfl_transformation_dag, task_id=task_pyspark, execution_date=20230411T000000, start_date=20230412T115032, end_date=20230412T115116
[2023-04-12T11:51:16.118+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 932 for task task_pyspark (Bash command failed. The command returned a non-zero exit code 1.; 7046)
[2023-04-12T11:51:16.162+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-12T11:51:16.181+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
