[2023-04-12T11:32:37.367+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [queued]>
[2023-04-12T11:32:37.390+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [queued]>
[2023-04-12T11:32:37.391+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T11:32:37.392+0000] {taskinstance.py:1289} INFO - Starting attempt 2 of 3
[2023-04-12T11:32:37.393+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T11:32:37.418+0000] {taskinstance.py:1309} INFO - Executing <Task(_PythonDecoratedOperator): task_pyspark> on 2023-04-11 00:00:00+00:00
[2023-04-12T11:32:37.452+0000] {standard_task_runner.py:55} INFO - Started process 3749 to run task
[2023-04-12T11:32:37.476+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'nfl_transformation_dag', 'task_pyspark', 'scheduled__2023-04-11T00:00:00+00:00', '--job-id', '914', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmp9h_u9y6b']
[2023-04-12T11:32:37.496+0000] {standard_task_runner.py:83} INFO - Job 914: Subtask task_pyspark
[2023-04-12T11:32:37.729+0000] {task_command.py:389} INFO - Running <TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [running]> on host a2e619923d04
[2023-04-12T11:32:37.854+0000] {taskinstance.py:1080} INFO - Dependencies not met for <TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2023-04-12T11:32:37.857+0000] {taskinstance.py:1080} INFO - Dependencies not met for <TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2023-04-12T11:32:37.871+0000] {local_task_job.py:151} INFO - Task is not able to be run
[2023-04-12T11:32:37.886+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nfl_transformation_dag
AIRFLOW_CTX_TASK_ID=task_pyspark
AIRFLOW_CTX_EXECUTION_DATE=2023-04-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-11T00:00:00+00:00
[2023-04-12T11:32:37.909+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-12T11:32:37.913+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'gcloud dataproc jobs submit pyspark                 --cluster=nfl-spark-cluster                 --region=europe-west6                 gs://nfl-data-lake_nfl-de-project/code/transformation_pyspark.py                 --                     --year=2020                     --season_type=2 ']
[2023-04-12T11:32:37.945+0000] {subprocess.py:86} INFO - Output:
[2023-04-12T11:32:44.119+0000] {subprocess.py:93} INFO - Job [3540131536174c13ab6a7cd02d68b977] submitted.
[2023-04-12T11:32:44.120+0000] {subprocess.py:93} INFO - Waiting for job output...
[2023-04-12T11:32:49.429+0000] {subprocess.py:93} INFO - =========== Cloud Dataproc Agent Error ===========
[2023-04-12T11:32:49.430+0000] {subprocess.py:93} INFO - java.io.FileNotFoundException: File not found: gs://nfl-data-lake_nfl-de-project/code/transformation_pyspark.py
[2023-04-12T11:32:49.431+0000] {subprocess.py:93} INFO - 	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.getFileStatus(GoogleHadoopFileSystemBase.java:958)
[2023-04-12T11:32:49.432+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:391)
[2023-04-12T11:32:49.433+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:342)
[2023-04-12T11:32:49.434+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.copyToLocalFile(FileSystem.java:2464)
[2023-04-12T11:32:49.435+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.copyToLocalFile(FileSystem.java:2433)
[2023-04-12T11:32:49.436+0000] {subprocess.py:93} INFO - 	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.copyToLocalFile(GoogleHadoopFileSystemBase.java:1614)
[2023-04-12T11:32:49.436+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.copyToLocalFile(FileSystem.java:2409)
[2023-04-12T11:32:49.437+0000] {subprocess.py:93} INFO - 	at com.google.cloud.hadoop.services.agent.util.HadoopUtil.download(HadoopUtil.java:127)
[2023-04-12T11:32:49.438+0000] {subprocess.py:93} INFO - 	at com.google.cloud.hadoop.services.agent.job.handler.AbstractJobHandler.downloadResources(AbstractJobHandler.java:502)
[2023-04-12T11:32:49.440+0000] {subprocess.py:93} INFO - 	at com.google.cloud.hadoop.services.agent.job.handler.AbstractJobHandler.prepareDriver(AbstractJobHandler.java:777)
[2023-04-12T11:32:49.441+0000] {subprocess.py:93} INFO - 	at com.google.cloud.hadoop.services.repackaged.com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
[2023-04-12T11:32:49.442+0000] {subprocess.py:93} INFO - 	at com.google.cloud.hadoop.services.repackaged.com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
[2023-04-12T11:32:49.443+0000] {subprocess.py:93} INFO - 	at com.google.cloud.hadoop.services.repackaged.com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
[2023-04-12T11:32:49.444+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2023-04-12T11:32:49.444+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2023-04-12T11:32:49.445+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[2023-04-12T11:32:49.445+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[2023-04-12T11:32:49.446+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2023-04-12T11:32:49.447+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2023-04-12T11:32:49.447+0000] {subprocess.py:93} INFO - 	at java.lang.Thread.run(Thread.java:750)
[2023-04-12T11:32:49.448+0000] {subprocess.py:93} INFO - ======== End of Cloud Dataproc Agent Error ========
[2023-04-12T11:33:15.910+0000] {subprocess.py:93} INFO - ERROR: (gcloud.dataproc.jobs.submit.pyspark) Job [3540131536174c13ab6a7cd02d68b977] failed with error:
[2023-04-12T11:33:15.911+0000] {subprocess.py:93} INFO - File not found: gs://nfl-data-lake_nfl-de-project/code/transformation_pyspark.py
[2023-04-12T11:33:16.190+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-12T11:33:16.207+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion.py", line 223, in task_pyspark
    operator.execute(context={})
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-12T11:33:16.222+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=nfl_transformation_dag, task_id=task_pyspark, execution_date=20230411T000000, start_date=20230412T113237, end_date=20230412T113316
[2023-04-12T11:33:16.257+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 914 for task task_pyspark (Bash command failed. The command returned a non-zero exit code 1.; 3749)
[2023-04-12T11:33:16.278+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-12T11:33:16.310+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
